#!/bin/bash
#SBATCH --job-name="hw4prob3"    # Name that appears in queue
#SBATCH --partition=small          # Resource group (small/large)
#SBATCH --account=csc726           # SLURM account
#SBATCH --nodes=1                  # Number of Nodes
#SBATCH --ntasks-per-node=44       # Number of CPU Cores
#SBATCH --mem=128gb                # Requested memory
#SBATCH --time=00-00:30:00         # Job duration in DD-HH:MM:SS
#SBATCH --mail-user=yangz223@wfu.edu
#SBATCH --mail-type=END,FAIL       # Updates to provide mail-user

# Load your software
module load compilers/gcc/12.3.0
module load mpi/openmpi/4.1.6

# Go to working directory
cd /deac/csc/classes/csc726/${USER}/1106Wed

# Execute your program

mpirun -n 32 hw4b 16777216